import { Inter } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./ClientWrapper"; // クライアントコンポーネントをインポート

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja" data-theme="bumblebee">
      <body className={inter.className}>
      <ClientWrapper>{children}</ClientWrapper></body>
    </html>
  );
}
